# Generated by Django 5.1.2 on 2025-08-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('ref', models.CharField(max_length=256, unique=True)),
                ('url', models.CharField(max_length=512)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
