services:
    live-updates-service:
      image: 944752351692.dkr.ecr.eu-west-1.amazonaws.com/live-updates-nzungu
      ports:
          - 8000:3412
      volumes:
          - /logs/live-updates-service:/logs
      environment:
          AWS_REAGION: ${AWS_REAGION}
          AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
          AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
          DYNAMO_DB_TABLE: ${DYNAMO_DB_TABLE}
          PORT: 3412
          ADMIN_KEY: live-updates-8d3922b7-cfca-4dd6-8cde-198c0c3649d8