# Base image
FROM python:3.9-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    default-libmysqlclient-dev \
    pkg-config \
    curl \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Working directory
WORKDIR /app
COPY . .

# Install Python dependencies 
RUN pip3 install -r requirements.txt 

# Download and install X-Ray daemon

RUN unzip packages/aws-xray-daemon-linux-3.x.zip -d /usr/local/bin \
    && chmod +x /usr/local/bin/xray

# Start X-Ray daemon and Gunicorn together
CMD xray -o & gunicorn --bind 0.0.0.0:80 --workers 4 main.wsgi:application