services:
    live-updates-service:
        image: 944752351692.dkr.ecr.eu-west-1.amazonaws.com/live-updates-nzungu
        ports:
            - 51592:80
        volumes:
            - /logs/live-updates-service:/logs
        environment:
            # AWS
            AWS_REAGION: ${AWS_REAGION}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            DYNAMO_DB_TABLE: ${DYNAMO_DB_TABLE}
            # Application
            PORT: 80
            ADMIN_KEY: live-updates-8d3922b7-cfca-4dd6-8cde-198c0c3649d8
    backend-service:
        depends_on:
            - live-updates-service
        image: 944752351692.dkr.ecr.eu-west-1.amazonaws.com/backend-nzungu:latest
        ports:
            - 80:80 
        volumes:
            - /logs/nzungu-backend:/logs
        environment:
            # Application
            APPLICATION_NAME: "Nzungu Backend v1.0.0"
            MAX_FILE_UPLOAD_SIZE: 2000000
            EXG_USD_ZWG: 40 
            # Live Updates Service 
            LIVE_UPDATES_ENDPOINT: "http://173.249.20.22:51592"
            LIVE_UPDATES_KEY: "live-updates-8d3922b7-cfca-4dd6-8cde-198c0c3649d8"
            # AWS
            AWS_REAGION: ${AWS_REAGION}
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            FILE_S3_BUCKET: "test-sandy-salts-nzungu"
            DYNAMO_DB_TABLE: "test-authorization-nzungu"
       