# Generated by Django 5.1.2 on 2025-08-03 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref', models.CharField(blank=True, max_length=256)),
                ('name', models.CharField(max_length=128)),
                ('icon', models.CharField(max_length=32)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductStockStatusFilter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref', models.CharField(blank=True, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('icon', models.CharField(max_length=32)),
                ('theme', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=32)),
                ('subtext', models.CharField(max_length=128)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('ref', models.CharField(max_length=256, unique=True)),
                ('url', models.CharField(max_length=512)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=64)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref', models.CharField(blank=True, max_length=256)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('price_usd', models.FloatField(default=0)),
                ('price_zwg', models.FloatField(default=0)),
                ('reorder_point', models.IntegerField(default=0)),
                ('expiry_day_buffer', models.IntegerField(default=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.productcategory')),
                ('image_uploaded', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.upload')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref', models.CharField(blank=True, max_length=256)),
                ('expires', models.DateField()),
                ('count', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
