# Generated by Django 5.1.2 on 2025-08-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstockstatusfilter',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
