# Generated by Django 5.1.2 on 2025-08-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0003_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_stock_status_filter',
        ),
    ]
