# ENVIRONMENT
FROM node:22-alpine
RUN apk update

# FILES
WORKDIR /app 
COPY . .
RUN mkdir logs

COPY package*.json ./

# Install dependencies using cache and retries
RUN npm set fetch-retries 5 \
    && npm set fetch-retry-maxtimeout 120000 \
    && npm ci --prefer-offline --no-audit --cache /root/.np
    
# INSTALL DEPENDENCIES
RUN npm install

# RUN THE APPLICATION
CMD node main.js