name: Backend Application

on:
    push:
        branches:
            - main

jobs:
    build-container:
        runs-on: ubuntu-latest
        steps:
            # Checkout
            - uses: actions/checkout@v4

            # Setup AWS
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4.3.1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: af-south-1

            # Build the container 
            - name: Build Backend Container
              run: |
                cd backend 
                docker build -t 944752351692.dkr.ecr.eu-west-1.amazonaws.com/backend-nzungu:latest .
            
            # Push the container to ECR
            - name: Push to ECR
              run: |
                aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 944752351692.dkr.ecr.eu-west-1.amazonaws.com
                docker push 944752351692.dkr.ecr.eu-west-1.amazonaws.com/backend-nzungu:latest