# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and deploy Nzungu application

# Event
on:
  push:
    branches: [ "main" ]

# Jobs
jobs:
  # Build frontend
  build-frontend:
    # OS
    runs-on: ubuntu-latest
    steps:
    
    # Checkout to branch 
    - uses: actions/checkout@v4
    
    # Setup nodejs
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        
    # Build frontend application
    - name: Build Webapp
      run: |
        cd webapp
        npm install
        npm run build

    # Upload frontend application to S3
    - name: Sync files to S3
      uses: aws-actions/s3-sync@v2
      with:
        bucket: ${{ secrets.S3_BUCKET }}
        region: af-south-1
        source-dir: webapp/dist
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
