# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and deploy Nzungu application

# Event
on:
  push:
    branches: [ "main" ]

# Job
jobs:
  # Build frontend
  build-frontend:
    # OS
    runs-on: ubuntu-latest
    steps:
    
    # Checkout to branch 
    - uses: actions/checkout@v4
    
    # Setup nodejs
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        
    # Build frontend application
    - name: Build Webapp
      run: |
        cd webapp
        npm install
        npm run build

    # Upload frontend application to S3 Bucket
    - uses: jakejarvis/s3-sync-action@master
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'af-south-1'  
        SOURCE_DIR: 'webapp/dist/'
